bus "i2c-16" "SCD 0000:04:00.0 SMBus master 1 bus 3"
bus "i2c-19" "SCD 0000:06:00.0 SMBus master 0 bus 0"
bus "i2c-22" "SCD 0000:06:00.0 SMBus master 0 bus 3"
bus "i2c-23" "SCD 0000:06:00.0 SMBus master 0 bus 4"
bus "i2c-24" "SCD 0000:06:00.0 SMBus master 0 bus 5"
bus "i2c-25" "SCD 0000:06:00.0 SMBus master 0 bus 6"

chip "k10temp-pci-00c3"
    label temp1 "Cpu temp sensor"

chip "tmp75-i2c-16-48"
    label temp1 "Outlet"

chip "tmp75-i2c-19-48"
    label temp1 "Management Card"

chip "amax31732-i2c-19-1c"
    label temp1 "PCB Temp Near Q3D"
    label temp2 "D0 Temp diode 0"
    label temp3 "D0 Temp diode 1"
    label temp4 "D1 Temp diode 0"
    label temp5 "D1 Temp diode 1"

chip "raa228228-i2c-24-45"
    label temp1 "POS0V75_VDDC_D0"
    label temp2 "POS3V3_OPTICS_A"
    ignore temp3

chip "isl68226-i2c-24-4c"
    label temp1 "POS1V2_HBM_D0"
    label temp2 "POS0V9_D0"
    label temp3 "POS0V75_D0"
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "isl68226-i2c-24-4f"
    label temp1 "POS1V2_VAA_PHY"
    label temp2 "POS0V75_VDD_PHY1"
    label temp3 "POS0V75_VDD_PHY2"
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "raa228228-i2c-25-45"
    label temp1 "POS0V75_VDDC_D1"
    label temp2 "POS3V3_OPTICS_B"
    ignore temp3

chip "isl68226-i2c-25-4c"
    label temp1 "POS1V2_HBM_D1"
    label temp2 "POS0V9_D1"
    label temp3 "POS0V75_D1"
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "isl68223-i2c-25-47"
    label temp1 "POS0V8_PBVDD"
    ignore temp2
    ignore temp3
    ignore temp4
    ignore temp5

chip "dps800-i2c-22-58"
    label temp1 "Power supply 1 inlet sensor"
    label temp2 "Power supply 1 secondary hotspot sensor"
    label temp3 "Power supply 1 primary hotspot sensor"

    ignore fan3
    ignore fan4

chip "dps800-i2c-23-58"
    label temp1 "Power supply 2 inlet sensor"
    label temp2 "Power supply 2 secondary hotspot sensor"
    label temp3 "Power supply 2 primary hotspot sensor"

    ignore fan3
    ignore fan4

chip "pmbus-i2c-22-58"
    label temp1 "Power supply 1 inlet sensor"
    label temp2 "Power supply 1 secondary hotspot sensor"
    label temp3 "Power supply 1 primary hotspot sensor"

    ignore fan3
    ignore fan4

chip "pmbus-i2c-23-58"
    label temp1 "Power supply 2 inlet sensor"
    label temp2 "Power supply 2 secondary hotspot sensor"
    label temp3 "Power supply 2 primary hotspot sensor"

    ignore fan3
    ignore fan4

chip "nvme-pci-0500"
    ignore temp2
    ignore temp3
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7
