# Broadcom DNX SAI definitions
LIBSAIBCM_DNX_VERSION = 15.2.1.0.0.0.11.3
LIBSAIBCM_DNX_BRANCH_NAME = SAI_15.2.1_GA

LIBSAIBCM_DNX_URL_PREFIX = "$(BUILD_PUBLIC_URL)/sai/sai-broadcom/$(LIBSAIBCM_DNX_BRANCH_NAME)/$(LIBSAIBCM_DNX_VERSION)/dnx"

# SAI module for DNX Asic family
BRCM_DNX_SAI = libsaibcm_dnx_$(LIBSAIBCM_DNX_VERSION)_amd64.deb
$(BRCM_DNX_SAI)_URL = "$(LIBSAIBCM_DNX_URL_PREFIX)/$(BRCM_DNX_SAI)"

# Package registration
SONIC_ONLINE_DEBS += $(BRCM_DNX_SAI)

# Version handling
$(BRCM_DNX_SAI)_SKIP_VERSION=y
