bus "i2c-21" "SCD 0000:01:00.0 SMBus master 0 bus 0"
bus "i2c-22" "SCD 0000:01:00.0 SMBus master 0 bus 1"
bus "i2c-25" "SCD 0000:01:00.0 SMBus master 0 bus 4"

chip "nvme-pci-0500"
    ignore temp2
    ignore temp3
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "raa228228-i2c-25-4c"
    label temp1 "POS0V75_VDDC_JE0"
    label temp2 "POS0V75_RTVDD_JE0"
    ignore temp3

chip "raa228228-i2c-25-4d"
    label temp1 "POS0V75_VDDC_JE1"
    label temp2 "POS0V75_RTVDD_JE1"
    ignore temp3

chip "isl68221-i2c-25-54"
    label temp1 "POS1V2_HBM0_VDD_JE0"
    label temp2 "POS1V2_HBM1_VDD_JE0"
    label temp3 "POS1V2_TVDD_JE0"
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "isl68221-i2c-25-55"
    label temp1 "POS1V2_HBM0_VDD_JE1"
    label temp2 "POS1V2_HBM1_VDD_JE1"
    label temp3 "POS1V2_TVDD_JE1"
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "isl68225-i2c-25-61"
    label temp1 "QSFP_3V3_LEFT"
    label temp2 "QSFP_3V3_RIGHT"
    ignore temp3
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "dps800-i2c-21-58"
    label temp1 "Power supply 1 inlet temp sensor"
    label temp2 "Power supply 1 secondary hotspot sensor"
    label temp3 "Power supply 1 primary hotspot temp sensor"

    ignore fan3
    ignore fan4

chip "dps800-i2c-22-58"
    label temp1 "Power supply 2 inlet temp sensor"
    label temp2 "Power supply 2 secondary hotspot sensor"
    label temp3 "Power supply 2 primary hotspot temp sensor"

    ignore fan3
    ignore fan4

