bus "i2c-6" "SCD 0000:07:00.0 SMBus master 0 bus 0"
bus "i2c-12" "SCD 0000:07:00.0 SMBus master 0 bus 6"
bus "i2c-13" "SCD 0000:07:00.0 SMBus master 1 bus 0"
bus "i2c-14" "SCD 0000:07:00.0 SMBus master 1 bus 1"
bus "i2c-15" "SCD 0000:07:00.0 SMBus master 1 bus 2"
bus "i2c-16" "SCD 0000:07:00.0 SMBus master 1 bus 3"

bus "i2c-35" "SCD 0000:09:00.0 SMBus master 0 bus 0"
bus "i2c-36" "SCD 0000:09:00.0 SMBus master 0 bus 1"
bus "i2c-37" "SCD 0000:09:00.0 SMBus master 0 bus 2"

bus "i2c-3" "SMBus PIIX4 adapter port 1 at 0b20"

chip "k10temp-pci-00c3"
    label temp1 "CPU internal"

chip "tmp75-i2c-6-48"
    label temp1 "Front panel"

chip "tmp75-i2c-12-49"
    label temp1 "Ambient"

chip "xdpe1e496b-i2c-3-68"
    label temp1 "CPU VRM POS1V1_MEM"
    label temp2 "CPU VRM POS0V8_VDDCR"
    label temp3 "CPU VRM POS0V8_VDDMISC"
    label temp4 "CPU VRM POS0V8_VDDSOC"

chip "tmp431-i2c-35-4c"
    label temp1 "Back center PCB"
    label temp2 "TH6 diode 0"

chip "tmp431-i2c-36-4c"
    label temp1 "Front left PCB"
    label temp2 "TH6 diode 1"

chip "tmp431-i2c-37-4c"
    label temp1 "Back left PCB"
    label temp2 "TH6 diode 2"

chip "tmp75-i2c-16-48"
    label temp1 "Rear card"

chip "pmbus-i2c-15-52"
    label temp1 "PSU 1 internal sensor"
chip "pmbus-i2c-15-53"
    label temp1 "PSU 2 internal sensor"
chip "pmbus-i2c-15-54"
    label temp1 "PSU 3 internal sensor"
chip "pmbus-i2c-15-55"
    label temp1 "PSU 4 internal sensor"
chip "pmbus-i2c-16-52"
    label temp1 "PSU 5 internal sensor"

chip "nvme-pci-0100"
    ignore temp2
    ignore temp3
