# p4lang package

# Main target: p4lang-pi
P4LANG_PI_VERSION = 0.1.3
P4LANG_PI_VERSION_FULL = $(P4LANG_PI_VERSION)-2

export P4LANG_PI_VERSION
export P4LANG_PI_VERSION_FULL

P4LANG_PI = p4lang-pi_$(P4LANG_PI_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(P4LANG_PI)_SRC_PATH = $(SRC_PATH)/p4lang
$(P4LANG_PI)_DEPENDS = $(PROTOBUF) $(PROTOBUF_LITE) $(PROTOC32) $(PYTHON3_PROTOBUF) $(GRPC) $(GRPC_CPP) $(PYTHON3_GRPC) $(PROTOBUF_DEV) $(PROTOC_DEV) $(PROTOBUF_COMPILER) $(GRPC_DEV) $(GRPC_CPP_DEV) $(GRPC_COMPILER)
$(P4LANG_PI)_RDEPENDS = $(PROTOBUF) $(PROTOBUF_LITE) $(PROTOC32) $(PYTHON3_PROTOBUF) $(GRPC) $(GRPC_CPP) $(PYTHON3_GRPC) $(PROTOBUF_DEV) $(PROTOC_DEV) $(PROTOBUF_COMPILER) $(GRPC_DEV) $(GRPC_CPP_DEV) $(GRPC_COMPILER)
SONIC_MAKE_DEBS += $(P4LANG_PI)

# p4lang-bmv2

P4LANG_BMV2_VERSION = 1.15.0
P4LANG_BMV2_VERSION_FULL = $(P4LANG_BMV2_VERSION)-9

export P4LANG_BMV2_VERSION
export P4LANG_BMV2_VERSION_FULL

P4LANG_BMV2 = p4lang-bmv2_$(P4LANG_BMV2_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(P4LANG_BMV2)_SRC_PATH = $($(P4LANG_PI)_SRC_PATH)
$(P4LANG_BMV2)_DEPENDS = $(P4LANG_PI)
$(P4LANG_BMV2)_RDEPENDS = $(P4LANG_PI)
SONIC_MAKE_DEBS += $(P4LANG_BMV2)

# p4lang-p4c

P4LANG_P4C_VERSION = 1.2.4.2
P4LANG_P4C_VERSION_FULL = $(P4LANG_P4C_VERSION)-3

export P4LANG_P4C_VERSION
export P4LANG_P4C_VERSION_FULL

P4LANG_P4C = p4lang-p4c_$(P4LANG_P4C_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(P4LANG_P4C)_SRC_PATH = $($(P4LANG_PI)_SRC_PATH)
$(P4LANG_P4C)_DEPENDS = $(P4LANG_BMV2)
$(P4LANG_P4C)_WHEEL_DEPENDS = $(SCAPY)
$(P4LANG_P4C)_RDEPENDS = $(P4LANG_BMV2)
SONIC_MAKE_DEBS += $(P4LANG_P4C)
